<?php
$CONFIG = array();
$CONFIG['mysql.host'] = array('type' => 'string', 'value' => 'localhost');
$CONFIG['mysql.user'] = array('type' => 'string', 'value' => 'soluROOTzink');
$CONFIG['mysql.pass'] = array('type' => 'string', 'value' => 'DkLhbARKpekyZqQ2yRqk');
$CONFIG['mysql.db'] = array('type' => 'string', 'value' => 'soluzink');
$CONFIG['debug'] = array('type' => 'boolean', 'value' => 0);
$CONFIG['langs.avaliable'] = array('type' => 'array', 'value' => array('es','en'));
$CONFIG['langs.default'] = array('type' => 'string', 'value' => 'es');
$CONFIG['secretkey.1'] = array('type' => 'string', 'value' => '3KTECUM0sOIIZGWZkvbHXgsQwWfCmEVlem3DEg');
$CONFIG['secretkey.2'] = array('type' => 'string', 'value' => 'AkNKae33g2B0WZKlUTbxRe6JDPzk3DEglsgsQw');
$CONFIG['profile.default.image'] = array('type' => 'string', 'value' => '/assets/images/profile/default.png');
$CONFIG['maintenance'] = array('type' => 'boolean', 'value' => false);
$CONFIG['lastMaintenanceTimestamp'] = array('type' => 'int', 'value' => 1499499588);
$CONFIG['CSRF.expire.interval'] = array('type' => 'int', 'value' => 900);
$CONFIG['facebook.account.name'] = array('type' => 'string', 'value' => 'soluzink');
$CONFIG['twitter.account.name'] = array('type' => 'string', 'value' => 'soluzink');
$CONFIG['login.attempts.interval'] = array('type' => 'int', 'value' => 1800);
$CONFIG['login.attempts.max'] = array('type' => 'int', 'value' => 5);
$CONFIG['login.seconds.delay'] = array('type' => 'int', 'value' => 2);
$CONFIG['contact.min.interval'] = array('type' => 'int', 'value' => 300);
$CONFIG['contact.message.minlength'] = array('type' => 'int', 'value' => 50);
$CONFIG['contact.message.maxlength'] = array('type' => 'int', 'value' => 700);
$CONFIG['register.accountscreate.interval'] = array('type' => 'int', 'value' => 86400);
$CONFIG['register.accountscreate.max'] = array('type' => 'int', 'value' => 1);
$CONFIG['register.passsword.strenght'] = array('type' => 'enum', 'value' => 3, 'possibleValues' => array(0,1,2,3));
$CONFIG['listing.default.results'] = array('type' => 'int', 'value' => 10);
$CONFIG['userlogged.checkonline.interval'] = array('type' => 'int', 'value' => 50);
$CONFIG['listing.sort.dir'] = array('type' => 'enum', 'value' => 'DESC', 'possibleValues' => array('ASC','DESC'));
$CONFIG['recover.attempts.interval'] = array('type' => 'int', 'value' => 600);
$CONFIG['recover.attempts.max'] = array('type' => 'int', 'value' => 3);
$CONFIG['api.jquery.vex-theme'] = array('type' => 'string', 'value' => 'vex-theme-os');
$CONFIG['timezone.default.weekdaystart'] = array('type' => 'enum', 'value' => 'S', 'possibleValues' => array('S','M'));
$CONFIG['braintree.merchantId'] = array('type' => 'string', 'value' => 'n5bpzdygcqdngmsf');
$CONFIG['braintree.publicKey'] = array('type' => 'string', 'value' => '5tszfsfxbn3xsvpq');
$CONFIG['braintree.privateKey'] = array('type' => 'string', 'value' => 'd7edab66f073fbde382da9f68b67043e');
$CONFIG['braintree.merchantCurrency.EUR'] = array('type' => 'string', 'value' => 'soluzinkEUR');
$CONFIG['braintree.merchantCurrency.USD'] = array('type' => 'string', 'value' => 'soluzinkUSD');
$CONFIG['braintree.merchantCurrency.GBP'] = array('type' => 'string', 'value' => 'soluzinkGBP');
$CONFIG['php.profile.maximagesize'] = array('type' => 'int', 'value' => 0);
$CONFIG['profile.photos.pxsize'] = array('type' => 'int', 'value' => 230);
$CONFIG['profile.blockaccount.afterwrongpasstimes'] = array('type' => 'int', 'value' => 5);
$CONFIG['profile.blockaccount.afterwrongcodetimes'] = array('type' => 'int', 'value' => 5);
$CONFIG['profile.blockaccount.resendcodeinterval'] = array('type' => 'int', 'value' => 300);
$CONFIG['opentok.apikey'] = array('type' => 'string', 'value' => '45946612');
$CONFIG['opentok.secretkey'] = array('type' => 'string', 'value' => '9d01f5111069e2c01a757d35c7ec74333871f266');
$CONFIG['session.defaultlenghtmins'] = array('type' => 'int', 'value' => 30);
$CONFIG['payments.enabled.global'] = array('type' => 'boolean', 'value' => true);
$CONFIG['remindersession.whenminsleft'] = array('type' => 'int', 'value' => 60);
$CONFIG['userlogged.checksessions.interval'] = array('type' => 'int', 'value' => 10);
$CONFIG['chat.host'] = array('type' => 'string', 'value' => 'sandbox.soluzink.com');
$CONFIG['chat.port'] = array('type' => 'int', 'value' => 9000);
$CONFIG['profile.description.minlength'] = array('type' => 'int', 'value' => 50);
$CONFIG['recaptcha.publickey'] = array('type' => 'string', 'value' => '6LfAwhUUAAAAAPodcLeySDlnjTQsSk0UwT1nDB9c');
$CONFIG['recaptcha.secretkey'] = array('type' => 'string', 'value' => '6LfAwhUUAAAAAJP9OawvvEIgVsozCcCYBrbp1fJe');
$CONFIG['admin.login.maxattempts'] = array('type' => 'int', 'value' => 5);
$CONFIG['admin.loginattempts.interval'] = array('type' => 'int', 'value' => 300);
$CONFIG['admin.logs.maxtoshow'] = array('type' => 'int', 'value' => 30);
$CONFIG['admin.charts.visits.interval'] = array('type' => 'int', 'value' => 7);
$CONFIG['admin.session.timeout'] = array('type' => 'int', 'value' => 1800);
$CONFIG['sessionnow.checker.interval'] = array('type' => 'int', 'value' => 60); //in seconds
/*CONFIGURAR PARA PODER ENVIAR PAGOS */
$CONFIG['paypal.security.userid'] = array('type' => 'int', 'value' => 0);
$CONFIG['paypal.security.password'] = array('type' => 'string', 'value' => 0);
$CONFIG['paypal.security.signature'] = array('type' => 'string', 'value' => 0);
$CONFIG['paypal.security.appid'] = array('type' => 'string', 'value' => 0);
$CONFIG['default.currency'] = array('type' => 'string', 'value' => 'EUR');